<?php

namespace App\Models;

use App\Common\Enums\SystemCode;

class Task extends Model
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(column="id", type="integer", length=20, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(column="group_id", type="integer", length=20, nullable=false)
     */
    public $groupId;

    /**
     *
     * @var string
     * @Column(column="detail", type="string", length=1000, nullable=false)
     */
    public $detail;

    /**
     *
     * @var string
     * @Column(column="begin_at", type="string", nullable=true)
     */
    public $beginAt;

    /**
     *
     * @var string
     * @Column(column="end_at", type="string", nullable=true)
     */
    public $endAt;

    /**
     *
     * @var string
     * @Column(column="created_at", type="string", nullable=true)
     */
    public $createdAt;

    /**
     *
     * @var string
     * @Column(column="updated_at", type="string", nullable=true)
     */
    public $updatedAt;

    /**
     *
     * @var integer
     * @Column(column="status", type="integer", length=4, nullable=false)
     */
    public $status;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("dtm");
        $this->setSource("task");
        parent::initialize();
    }

    public function beforeCreate()
    {
        $this->beginAt = date('Y-m-d H:i:s');
        $this->status = SystemCode::TASK_STATUS_READY;
        parent::beforeCreate(); // TODO: Change the autogenerated stub
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Task[]|Task|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Task|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'task';
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'id' => 'id',
            'group_id' => 'groupId',
            'detail' => 'detail',
            'begin_at' => 'beginAt',
            'end_at' => 'endAt',
            'created_at' => 'createdAt',
            'updated_at' => 'updatedAt',
            'status' => 'status'
        ];
    }

}
